name: Pipeline CTTU e BigQuery

# 1. OS GATILHOS (Quando o robô acorda?)
on:
  schedule:
    - cron: "0 3 * * *" # Todo dia às 3h da manhã
  pull_request:
    branches:
      - main
      - development # Avalia o código toda vez que alguém tentar juntar algo nessas branches

# 2. O TRABALHO (A receita de bolo)
jobs:
  executar-e-testar:
    runs-on: ubuntu-latest # O computador novinho que o GitHub alugou pra você

    steps:
      - name: 1. Baixar o código do repositório
        uses: actions/checkout@v4

      - name: 2. Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 3. Instalar bibliotecas e o "Fiscal de Código" (flake8) e DBT
        run: |
          pip install requests google-cloud-bigquery flake8 dbt-bigquery

      - name: 4. Passar o Fiscal no código (Testar formatação)
        run: flake8 api.py --count --max-line-length=120 --statistics

      - name: 5. Criar arquivo de chave temporário e rodar o script
        env:
          MINHA_CHAVE_SECRETA: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$MINHA_CHAVE_SECRETA" > chave_google.json
          export GOOGLE_APPLICATION_CREDENTIALS="chave_google.json"
          python api.py
      - name: 6. Transformação (DBT RAW -> DBT MART)
        env:
          MINHA_CHAVE_SECRETA: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          # Garante que a chave do Google está configurada para o dbt usar
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/chave_google.json"
          
          # Entra na pasta onde o projeto dbt realmente está
          cd mobilidade_urbana
          
          # Roda o dbt para criar todas as tabelas finais
          dbt run --profiles-dir .

      - name: 7. Remover chave temporária
        if: always() # Roda mesmo se os steps anteriores falharem
        run: rm -f chave_google.json